/**
 * Renderers for the generated design docs, shared by the gen:* scripts
 * (which write them) and tests/generated-docs.test.ts (which fails when a
 * committed doc no longer matches its sources).
 */
import { clipFile, clipText, RECORDED_CLIPS } from '../src/audio/clips';
import { requiredClips } from '../src/audio/voiceScript';
import { BAND_GRADES, GRAPH, SKILLS } from '../src/core/skills';
import { tk } from '../src/i18n/i18n';
import { allLocales } from '../src/i18n/locales';

export const SKILL_GRAPH_DOC = 'design/skill-graph.md';
export const AUDIO_SCRIPT_DOC = 'design/audio-recording-script.md';

/** design/skill-graph.md from src/core/skills/catalog.ts and the skill names. */
export function renderSkillGraphDoc(): string {
  const gradeName = (g: number): string => (g < 1 ? 'Preschool (age 5)' : `Grade ${Math.floor(g)} / ${Math.floor(g)} одделение (age ${Math.floor(g) + 5})`);
  const lines: string[] = [
    '# Skill graph (generated)',
    '',
    'Generated by `npm run gen:skill-doc` from `src/core/skills/catalog.ts`. Do not edit by hand.',
    '',
    `**${SKILLS.length} skills**, ${GRAPH.playableSkills().length} playable in the vertical slice (✅). Band windows (grade position): ` +
      Object.entries(BAND_GRADES).map(([b, [lo, hi]]) => `${b} = [${lo}, ${hi})`).join(', ') +
      '. Unlocking uses *effective* prerequisites: the nearest playable ancestors, so unbuilt nodes never become walls.',
    '',
  ];

  let current = -1;
  for (const s of GRAPH.topo().sort((a, b) => a.grade - b.grade || a.id.localeCompare(b.id))) {
    const g = Math.floor(s.grade);
    if (g !== current) {
      if (current !== -1) lines.push('');
      current = g;
      lines.push(`## ${gradeName(s.grade)}`, '', '| | id | English | Македонски | pos | band | prerequisites | tags |', '|---|---|---|---|---|---|---|---|');
    }
    lines.push(
      `| ${GRAPH.isPlayable(s.id) ? '✅' : ''} | \`${s.id}\` | ${tk('en', `skill.${s.id}`)} | ${tk('mk', `skill.${s.id}`)} | ${s.grade.toFixed(1)} | ${s.band} | ${s.prereqs.map((p) => `\`${p}\``).join(', ') || '—'} | ${s.tags.join(', ')} |`,
    );
  }

  lines.push('', '## DAG', '', '```mermaid', 'flowchart LR');
  for (const band of ['A', 'B', 'C'] as const) {
    lines.push(`  subgraph Band_${band}["Band ${band}"]`);
    for (const s of SKILLS.filter((x) => x.band === band)) {
      lines.push(`    ${s.id.replace(/\./g, '_')}["${tk('en', `skill.${s.id}`)}"]${GRAPH.isPlayable(s.id) ? ':::playable' : ''}`);
    }
    lines.push('  end');
  }
  for (const s of SKILLS) for (const p of s.prereqs) lines.push(`  ${p.replace(/\./g, '_')} --> ${s.id.replace(/\./g, '_')}`);
  lines.push('  classDef playable fill:#d8f3e6,stroke:#16804a', '```', '');
  return lines.join('\n');
}

/**
 * design/audio-recording-script.md from src/audio/voiceScript.ts, the locale
 * bundles and the recorded clips (the committed manifest; gen:clips passes
 * the folder listing it has just written).
 */
export function renderAudioScriptDoc(recorded: Readonly<Record<string, readonly string[]>> = RECORDED_CLIPS): string {
  const lines: string[] = [
    '# Audio recording script (generated)',
    '',
    'Generated by `npm run gen:audio-script` from `src/audio/voiceScript.ts` and the locale bundles.',
    'Record each line as a separate mono MP3 (44.1 kHz, ~48 kbps, under 150 KB), ~200 ms of silence trimmed at both ends,',
    'friendly and unhurried, named exactly as in the *file* column.',
    '',
    '**Adding recordings:** drop the files into `public/audio/<locale>/` (e.g. `public/audio/mk/num.7.mp3`), then run',
    '`npm run gen:clips` (the build also does it). It lists them in `src/audio/clips.manifest.json` and ticks them off',
    'below; commit the files, the manifest and this script together. The game plays a line from recordings as soon as',
    'every clip of that line exists. Grown-ups → Voices lists what is still missing.',
    '',
    'Numbers 21–99 are composed from tens + units (+ "и" in Macedonian), so only these number words are needed.',
    '',
  ];

  for (const loc of allLocales()) {
    const clips = requiredClips(loc.id);
    const done = new Set(recorded[loc.id] ?? []);
    const n = clips.filter((id) => done.has(id)).length;
    lines.push(`## ${loc.nativeName} (${loc.id}) — ${clips.length} clips, ${n} recorded`, '');
    lines.push('| # | file | text | recorded |', '|---|---|---|---|');
    clips.forEach((id, i) => lines.push(`| ${i + 1} | \`${clipFile(id)}\` | ${clipText(loc.id, id).replace(/\|/g, '\\|')} | ${done.has(id) ? 'yes' : ''} |`));
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}
