/**
 * Generates design/skill-graph.md from the catalog, so the documented graph
 * can never drift from the code.   npm run gen:skill-doc
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { BAND_GRADES, GRAPH, SKILLS } from '../src/core/skills';
import { tk } from '../src/i18n/i18n';

const gradeName = (g: number): string => (g < 1 ? 'Preschool (age 5)' : `Grade ${Math.floor(g)} / ${Math.floor(g)} одделение (age ${Math.floor(g) + 5})`);
const lines: string[] = [
  '# Skill graph (generated)',
  '',
  'Generated by `npm run gen:skill-doc` from `src/core/skills/catalog.ts`. Do not edit by hand.',
  '',
  `**${SKILLS.length} skills**, ${GRAPH.playableSkills().length} playable in the vertical slice (✅). Band windows (grade position): ` +
    Object.entries(BAND_GRADES).map(([b, [lo, hi]]) => `${b} = [${lo}, ${hi})`).join(', ') +
    '. Unlocking uses *effective* prerequisites: the nearest playable ancestors, so unbuilt nodes never become walls.',
  '',
];

let current = -1;
for (const s of GRAPH.topo().sort((a, b) => a.grade - b.grade || a.id.localeCompare(b.id))) {
  const g = Math.floor(s.grade);
  if (g !== current) {
    if (current !== -1) lines.push('');
    current = g;
    lines.push(`## ${gradeName(s.grade)}`, '', '| | id | English | Македонски | pos | band | prerequisites | tags |', '|---|---|---|---|---|---|---|---|');
  }
  lines.push(
    `| ${GRAPH.isPlayable(s.id) ? '✅' : ''} | \`${s.id}\` | ${tk('en', `skill.${s.id}`)} | ${tk('mk', `skill.${s.id}`)} | ${s.grade.toFixed(1)} | ${s.band} | ${s.prereqs.map((p) => `\`${p}\``).join(', ') || '—'} | ${s.tags.join(', ')} |`,
  );
}

lines.push('', '## DAG', '', '```mermaid', 'flowchart LR');
for (const band of ['A', 'B', 'C'] as const) {
  lines.push(`  subgraph Band_${band}["Band ${band}"]`);
  for (const s of SKILLS.filter((x) => x.band === band)) {
    lines.push(`    ${s.id.replace(/\./g, '_')}["${tk('en', `skill.${s.id}`)}"]${GRAPH.isPlayable(s.id) ? ':::playable' : ''}`);
  }
  lines.push('  end');
}
for (const s of SKILLS) for (const p of s.prereqs) lines.push(`  ${p.replace(/\./g, '_')} --> ${s.id.replace(/\./g, '_')}`);
lines.push('  classDef playable fill:#d8f3e6,stroke:#16804a', '```', '');

const out = resolve(__dirname, '../design/skill-graph.md');
writeFileSync(out, lines.join('\n'));
console.log(`wrote ${out}`);
