/**
 * Generates design/audio-recording-script.md: every clip a voice actor must
 * record per locale, with its text, file name and the total budget.
 *   npm run gen:audio-script
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { RECORDED_CLIPS } from '../src/audio/clips';
import { requiredClips } from '../src/audio/voiceScript';
import { tk } from '../src/i18n/i18n';
import { allLocales } from '../src/i18n/locales';

const lines: string[] = [
  '# Audio recording script (generated)',
  '',
  'Generated by `npm run gen:audio-script` from `src/audio/voiceScript.ts` and the locale bundles.',
  'Record each line as a separate mono MP3 (44.1 kHz, ~48 kbps), ~200 ms of silence trimmed at both ends,',
  'friendly and unhurried. Save as `public/audio/<locale>/<clip-id>.mp3` and list the id in `src/audio/clips.ts`.',
  'Numbers 21–99 are composed from tens + units (+ "и" in Macedonian), so only these number words are needed.',
  '',
];

for (const loc of allLocales()) {
  const clips = requiredClips(loc.id);
  const done = new Set(RECORDED_CLIPS[loc.id] ?? []);
  const text = (id: string): string => (id.startsWith('voice.') ? tk(loc.id, id, {}) : tk(loc.id, `clip.${id}`));
  lines.push(`## ${loc.nativeName} (${loc.id}) — ${clips.length} clips, ${done.size} recorded`, '');
  lines.push('| # | file | text | recorded |', '|---|---|---|---|');
  clips.forEach((id, i) => lines.push(`| ${i + 1} | \`${id}.mp3\` | ${text(id).replace(/\|/g, '\\|')} | ${done.has(id) ? 'yes' : ''} |`));
  lines.push('');
}

const out = resolve(__dirname, '../design/audio-recording-script.md');
writeFileSync(out, `${lines.join('\n')}\n`);
console.log(`wrote ${out}`);
